# Generated by Django 5.2.1 on 2025-05-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
