# Generated by Django 5.2.1 on 2025-05-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_produit_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnerproduit',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perteproduit',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
