# Generated by Django 5.2.1 on 2025-06-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_alter_approvisionnerproduit_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="date_expiration",
        ),
    ]
