# Generated by Django 5.2.1 on 2025-06-30 01:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_remove_produit_date_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="venteproduit",
            name="transaction_id",
            field=models.CharField(
                db_index=True, default=uuid.uuid4, editable=False, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="venteproduit",
            name="date_vente",
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
