# Generated by Django 5.2.1 on 2025-06-30 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_venteproduit_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venteproduit",
            name="date_vente",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="venteproduit",
            name="transaction_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
