# Generated by Django 5.2.1 on 2025-07-21 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0007_alter_venteproduit_date_vente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("gestionnaire", "Gestionnaire"),
                    ("client", "Client"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("en_ligne", "Paiement en ligne"),
                            ("cash", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("carte", "Carte bancaire"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("echoue", "Échoué"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_paiement", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="stock.client",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="venteproduit",
            name="paiement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.paiement",
            ),
        ),
    ]
