# Generated by Django 5.2.1 on 2025-09-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_client_user_alter_user_role_paiement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venteproduit",
            name="prix_unitaire",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
