# Generated by Django 5.2.1 on 2025-09-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_venteproduit_prix_unitaire"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venteproduit",
            old_name="prix_unitaire",
            new_name="prixUnitaire",
        ),
    ]
